import React from "react";
import { render } from "./test-utils";
import { App } from "./App";

/**
 * Test that the app renders without crashing. This was generated by create-react-app.
 */
test("renders learn react link", () => {
  render(<App />);
  // const linkElement = screen.getByText(/learn chakra/i);
  // // test that linkElement is in the document
  // expect(linkElement).toBeInTheDocument();
});
